### PR TITLE
[Finishes 160131185] Create the homepage for the application

### PR DESCRIPTION
**Pull request by SilasKenneth**
#### What this pull request does
Creates the homepage for the fast-food-fast website
##### Description of task to be completed
 Create the homepage
    -  Add links to `login` and `signup`
    - The main page layout
##### Relevant pivotal tracker story
[#160131185](https://www.pivotaltracker.com/n/projects/2194200/stories/160131185)
##### How to test
  - Clone the repo ``git clone https://github.com/SilasKenneth/fast-food-fast-ui.git``
  -  Go to the fast-food-fast-ui directory and head to UI folder
  - Open the index.html file in your browser and that should work

#### Screenshot
Homepage

### CODE REVIEW

**Comment by danielotieno** [comment]
Neat

**Comment by SilasKenneth** [comment]
Thanks @danielotieno

**Comment by Bryan-Cee** [comment]
Neat UI

**Comment by SilasKenneth** [comment]
Thanks @Bryan-Cee

**Comment by bettblake08** [comment]
That's well done!

**Pull request merged**
